export type User = {
  _id: string; //its different from the auth0Id because the _id is generated by MongoDB
  email: string;
  name: string;
  addressLine1: string;
  city: string;
  country: string;
};
