export type User = {
  _id: string; //its different from the auth0Id because the _id is generated by MongoDB
  email: string;
  name: string;
  addressLine1: string;
  city: string;
  country: string;
};

export type MenuItem = {
  _id: string;
  name: string;
  price: number;
};

export type Restaurant = {
  _id: string; // Identifier for the restaurant
  user: string; // Identifier for the user who owns the restaurant
  restaurantName: string;
  address: string;
  city: string;
  country: string;
  deliveryPrice: number;
  estimatedDeliveryTime: number;
  cuisines: string[];
  menuItems: MenuItem[];
  imageUrl: string;
  lastUpdated: string;
};
